---
abstract: "allow or forbid implicitly converting references into\nstrings"
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  ExtUtils::CBuilder: 0
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: stringification
provides:
  stringification:
    file: lib/stringification.pm
    version: 0.01_001
requires:
  XSLoader: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_001
