---
abstract: "allow or forbid implicitly converting references into\nstrings"
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  ExtUtils::CBuilder: 0
  Test::Fatal: 0
  Test::More: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: stringification
provides:
  stringification:
    file: lib/stringification.pm
    version: 0.01_004
requires:
  XSLoader: 0
  perl: v5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_004
